-- CASE FILE — assignment vlog · seed data
-- GENERATED by scripts/gen-seed.mjs from src/data/cases.ts, extras.ts, profile.ts.
-- Regenerate with:  node scripts/gen-seed.mjs
-- Safe to run more than once (every statement is "on conflict do nothing").
-- Run AFTER supabase/schema.sql.

-- ============================================================
-- SUBJECTS — the five course folders
-- ============================================================
insert into public.subjects (slug, case_number, title, short_title, description, folder_note, icon, sort_order) values
  ('english-for-the-arts', '001', 'ENGLISH FOR THE ARTS', 'English for the Arts', 'How language, literature, and communication shape the arts — and how to write about them well.', 'Words and images keep borrowing from each other. This folder follows the borrowings.', 'book', 1),
  ('creative-design-thinking', '002', 'CREATIVE DESIGN THINKING', 'Creative Design Thinking', 'Creative problem-solving you can show: briefs, ideas, prototypes, and the reasoning behind them.', 'Good ideas are moves through ambiguity — with receipts.', 'bulb', 2),
  ('drawing-techniques', '003', 'DRAWING TECHNIQUES & PROCESS', 'Drawing Techniques & Process', 'Drawing fundamentals — seeing, mark-making, value, composition — with the process kept visible.', 'Look longer, record more, keep the drafts.', 'pencil', 3),
  ('computer-graphics', '004', 'INTRODUCTION TO COMPUTER GRAPHICS', 'Introduction to Computer Graphics', 'How software turns instructions into images: pixels, vectors, color, layers, and delivery.', 'Every image is a system you can inspect.', 'monitor', 4),
  ('visual-communication', '005', 'INTRODUCTION TO VISUAL COMMUNICATION', 'Introduction to Visual Communication', 'How images, symbols, typography, and color carry ideas — and how to design messages that land.', 'The frame, the signal, the silence — and the relationships between them.', 'eye', 5)
on conflict (slug) do nothing;

-- ============================================================
-- ENTRIES — every assignment (subject link resolved by slug)
-- ============================================================
insert into public.entries (subject_id, code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
select s.id, v.*
from (values
    (
    '001-01',
    'introduction-to-english-for-the-arts',
    'Introduction to English for the Arts',
    '2026-08-24'::date,
    'First entry: what it means to read an artwork the way you read a sentence.',
    'The arts are not separate from language — they are systems of choices. A title, a gesture, a material, or a rhythm can steer an audience toward an interpretation before a single word of explanation is added.',
    $j$["Meaning is constructed through signs, choices, and context.","Audience knowledge changes how a work is read.","Describing and interpreting are two different steps."]$j$::jsonb,
    $j$["Start with what is observable before making a claim about intention.","Use precise verbs: frames, contrasts, repeats, interrupts, suggests."]$j$::jsonb,
    'Pick one artwork and write two sentences about it: one purely descriptive, one interpretive. Label what changed between them.',
    'This entry set up the habit the whole folder runs on: look closely, describe first, interpret second.',
    1
  ),
    (
    '001-02',
    'language-and-artistic-expression',
    'Language and Artistic Expression',
    '2026-08-31'::date,
    'How artists bend words — rhythm, texture, ambiguity, voice.',
    'Poetry, lyrics, scripts, captions, and artist statements all use language differently, and their form shapes how a reader moves through the meaning.',
    $j$["Tone comes from diction, rhythm, syntax, and point of view.","Figurative language links a concrete image to an abstract idea.","Form is part of the message, not decoration around it."]$j$::jsonb,
    $j$["Read aloud to hear pacing and emphasis.","Ask what the chosen form lets the artist do that a plain statement could not."]$j$::jsonb,
    'Rewrite one neutral sentence in three voices — intimate, urgent, detached — and note the choices that changed it.',
    'Expression becomes visible when you watch how the language performs, not just what it says.',
    2
  ),
    (
    '001-03',
    'literature-and-the-arts',
    'Literature and the Arts',
    '2026-09-07'::date,
    'Where stories, images, and performances borrow each other’s structures.',
    'Narrative is a pattern of change — a perspective, a sequence, a conflict, a transformation — and visual and performing arts can make those patterns spatial or physical.',
    $j$["Narrative can be linear, fragmented, circular, or implied.","Point of view controls what the audience knows, and when.","Adaptation is a conversation between forms, not a copy."]$j$::jsonb,
    $j$["Map who knows what at each moment of a work.","Compare what each medium makes visible, audible, or embodied."]$j$::jsonb,
    'Compare a short story with a visual adaptation and explain one narrative element that changed form.',
    'Story structure is a shared toolkit across every medium in this folder.',
    3
  ),
    (
    '001-04',
    'critical-reading-and-interpretation',
    'Critical Reading and Interpretation',
    '2026-09-14'::date,
    'Interpretation as a claim you can support, not a guess.',
    'Critical reading asks who made a work, for whom, under what conditions, and with which assumptions — the frame around the work becomes part of the reading.',
    $j$["A strong reading names an observation, explains its meaning, and acknowledges context.","Multiple readings can coexist when each is accountable to what is visible.","Questions are tools for discovering assumptions."]$j$::jsonb,
    $j$["Connect each claim to its support with a clear “because”.","Test your reading against a detail that seems to contradict it."]$j$::jsonb,
    'Write a three-part reading of one work — claim, support, reasoning — plus one question it cannot answer yet.',
    'A good reading stays curious while still making its reasoning visible.',
    4
  ),
    (
    '001-05',
    'rhetoric-and-audience',
    'Rhetoric and Audience',
    '2026-09-21'::date,
    'Every creative message imagines someone receiving it.',
    'Rhetoric is the study of persuasive choices — emotional, sensory, ethical, intellectual — and in the arts those choices quietly position an audience.',
    $j$["Audience expectations shape form and tone.","Ethos, pathos, and logos can overlap inside one work.","A message can invite, challenge, or resist its audience."]$j$::jsonb,
    $j$["Identify the assumed audience before judging whether a work works.","Notice how scale, proximity, and direct address change your role."]$j$::jsonb,
    'Annotate three audience cues in a poster, performance, or artwork, then describe the role each cue assigns you.',
    'Once you see the audience a work imagines, its choices start making sense.',
    5
  ),
    (
    '001-06',
    'writing-the-portfolio-note',
    'Writing the Portfolio Note',
    '2026-09-28'::date,
    'Turning rough notes into a short, clear written response.',
    'Academic writing in the arts is a crafted path for another reader: it makes your thinking visible so someone else can follow it, question it, or build on it.',
    $j$["Structure helps points accumulate instead of scattering.","Transitions show how ideas relate.","Revision is an act of clarifying, not just correcting."]$j$::jsonb,
    $j$["Read for the reader’s next question.","Cut general praise when a specific observation does more work."]$j$::jsonb,
    'Turn the notes from an earlier entry into a 200-word written response with one clear claim and two cited observations.',
    'Writing is where an assignment stops being private thinking and becomes something shareable.',
    6
  )
) as v(code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
join public.subjects s on s.slug = 'english-for-the-arts'
on conflict (code) do nothing;

insert into public.entries (subject_id, code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
select s.id, v.*
from (values
    (
    '002-01',
    'framing-the-brief',
    'Framing the Brief',
    '2026-09-01'::date,
    'Before any ideas: deciding what problem is actually worth solving.',
    'A brief translates a messy situation into a shared direction — the people, the context, and the change you want — while leaving room to discover things along the way.',
    $j$["A problem statement should describe a human need, not just a deliverable.","Constraints can focus creativity.","A brief is a hypothesis, so it can be revised."]$j$::jsonb,
    $j$["Ask who is affected and what success would feel like.","Separate symptoms from the underlying need."]$j$::jsonb,
    'Rewrite a vague project request as a user-centered “How might we…” question.',
    'A good brief opens the work up without deciding the ending.',
    1
  ),
    (
    '002-02',
    'empathy-and-observation',
    'Empathy and Observation',
    '2026-09-08'::date,
    'Collecting real observations before jumping to solutions.',
    'Observation moves design past assumptions: interviews, shadowing, artifact review, and mapping a real context all count as evidence about how people actually behave.',
    $j$["Record behavior and language, not only opinions.","Empathy is a method of understanding, not a performance of agreement.","Patterns only emerge across multiple observations."]$j$::jsonb,
    $j$["Write down exact phrases before summarizing.","Notice workarounds — they often reveal unmet needs."]$j$::jsonb,
    'Watch a routine for five minutes and record ten non-judgmental details before proposing anything.',
    'Specific people in specific contexts beat an abstract “audience” every time.',
    2
  ),
    (
    '002-03',
    'ideation-and-divergence',
    'Ideation and Divergence',
    '2026-09-15'::date,
    'Widening the search before choosing a direction.',
    'Divergent thinking values quantity, variety, and combination before evaluation — it makes room for unexpected associations that a first idea would never reach.',
    $j$["Separate idea generation from idea judgment.","Prompts and constraints can produce useful variety.","Building on someone else’s idea is a design skill."]$j$::jsonb,
    $j$["Change the medium: sketch, list, act, map, or remix.","Look for clusters of ideas rather than one “best” idea."]$j$::jsonb,
    'Generate twelve distinct responses to one brief, then group them by the need they address.',
    'More leads in, better direction out — divergence is what makes selection meaningful.',
    3
  ),
    (
    '002-04',
    'prototyping-as-a-question',
    'Prototyping as a Question',
    '2026-09-22'::date,
    'A prototype is a small, testable question made visible.',
    'Paper, role-play, storyboard, wireframe, or clickable flow — the fidelity of a prototype should match the question it is asking, not the polish you wish you had.',
    $j$["Make the smallest artifact that can produce useful feedback.","A prototype is not a promise; it is a learning instrument.","Failure is information when the question is clear."]$j$::jsonb,
    $j$["Name what you want to learn before you build.","Keep a record of what changed between versions."]$j$::jsonb,
    'Choose a concept and build one low-fidelity prototype that tests a single assumption.',
    'Prototypes turn ideas into something the world can answer.',
    4
  ),
    (
    '002-05',
    'feedback-and-iteration',
    'Feedback and Iteration',
    '2026-09-29'::date,
    'The first version is a lead, not a verdict.',
    'Feedback becomes actionable when it is tied to behavior, context, and a design decision — and iteration is a learning cycle, not endless polishing.',
    $j$["Ask what the person tried to do before asking what they liked.","Look for friction that repeats across sessions.","Explain why each change responds to what you saw."]$j$::jsonb,
    $j$["Record feedback without defending the work in the moment.","Prioritize by impact and confidence."]$j$::jsonb,
    'Turn three observations from a peer test into three changes, each with a one-line reason.',
    'Iteration keeps the work accountable to what people actually experience.',
    5
  ),
    (
    '002-06',
    'making-the-case',
    'Making the Case',
    '2026-10-06'::date,
    'The final rationale: brief, decisions, support, and next questions.',
    'A design presentation is an argument — it shows the path from framing to tested direction without hiding the uncertainty that remains.',
    $j$["Sequence the story around decisions, not just deliverables.","Show the support right beside the claim it backs.","Name what remains unresolved."]$j$::jsonb,
    $j$["Use before/after comparisons sparingly, and explain the tradeoff.","End with the next experiment, not a vague promise."]$j$::jsonb,
    'Write a one-page rationale: the brief, two evidence points, one tradeoff, and one next step.',
    'Creative choices stay credible when the reasoning is visible.',
    6
  )
) as v(code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
join public.subjects s on s.slug = 'creative-design-thinking'
on conflict (code) do nothing;

insert into public.entries (subject_id, code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
select s.id, v.*
from (values
    (
    '003-01',
    'seeing-before-marking',
    'Seeing Before Marking',
    '2026-09-03'::date,
    'Drawing starts as attention, not lines.',
    'Observation is selective — where you look, what you compare, which relationships matter — and drawing slows that selection down until it becomes deliberate.',
    $j$["Contour, proportion, negative space, and gesture are observational tools.","A drawing can record movement as well as shape.","Looking and marking should stay in conversation."]$j$::jsonb,
    $j$["Compare angles and relative distances instead of naming objects too quickly.","Use the page as a field of relationships."]$j$::jsonb,
    'Do a five-minute blind-contour study, then mark the places where looking and drawing diverged.',
    'Training the eye is training the hand — they develop together.',
    1
  ),
    (
    '003-02',
    'line-weight-and-gesture',
    'Line Weight and Gesture',
    '2026-09-10'::date,
    'What changes when the mark changes.',
    'Gesture drawing captures action and weight through speed, direction, and economy, while line weight adds hierarchy and a sense of touch.',
    $j$["A line can be structural, descriptive, expressive, or all three.","Speed changes what the hand prioritizes.","Variation in the mark creates visual rhythm."]$j$::jsonb,
    $j$["Try tools at different pressures and angles.","Let a few decisive marks carry the pose."]$j$::jsonb,
    'Draw the same pose three times — fast, slow, and one continuous line — then compare the three.',
    'A line is a record of movement between eye, hand, tool, and surface.',
    2
  ),
    (
    '003-03',
    'value-and-light',
    'Value and Light',
    '2026-09-17'::date,
    'Light organizes a scene into readable masses.',
    'Value describes relative lightness and darkness; even a limited range builds strong structure when the grouping is intentional.',
    $j$["Squinting reveals the large value families first.","Edges can be lost or found depending on light.","Contrast directs attention."]$j$::jsonb,
    $j$["Start with three values before adding nuance.","Find where the darkest dark and lightest light do the most work."]$j$::jsonb,
    'Make a three-value study of a simple object and circle the focal area.',
    'Value turns plain looking into an organized field of light and weight.',
    3
  ),
    (
    '003-04',
    'composition-and-space',
    'Composition and Space',
    '2026-09-24'::date,
    'The frame is part of the drawing.',
    'Composition is the arrangement of visual relationships inside and around the image — and negative space is an active player, not leftover emptiness.',
    $j$["Cropping changes narrative pressure.","Scale communicates importance and intimacy.","Directional lines can guide a viewer through the page."]$j$::jsonb,
    $j$["Rotate the page to check balance without habit.","Study the corners and margins, not only the subject."]$j$::jsonb,
    'Make two thumbnail compositions of the same objects — one calm, one tense — and explain the difference.',
    'Composition decides the order in which a viewer meets the work.',
    4
  ),
    (
    '003-05',
    'material-and-surface',
    'Material and Surface',
    '2026-10-01'::date,
    'Every tool leaves a signature.',
    'Graphite, ink, charcoal, paint, and digital brushes each bring different friction, edges, and possibilities to the same idea.',
    $j$["Surface affects speed, texture, and resistance.","Tool choice can echo the subject’s material qualities.","Experimenting is how you gather a personal reference library."]$j$::jsonb,
    $j$["Keep a mark library and name what each tool can do.","Use material contrast to separate layers or ideas."]$j$::jsonb,
    'Build a six-mark sampler and write down what each mark communicates.',
    'Material is never a neutral carrier — it participates in the meaning.',
    5
  ),
    (
    '003-06',
    'revision-and-reflection',
    'Revision and Reflection',
    '2026-10-08'::date,
    'Process becomes visible when you can explain the changes.',
    'Revision adds, removes, redraws, layers, or reframes — and reflection identifies which choices actually produced the strongest work.',
    $j$["Process notes turn intuition into transferable knowledge.","A revision should answer a visual problem.","Finished does not mean unexplained."]$j$::jsonb,
    $j$["Photograph the stages when possible.","Name one successful decision and one open question."]$j$::jsonb,
    'Annotate three stages of one drawing and the question each stage answered.',
    'Reflection closes the entry and quietly sets up the next one.',
    6
  )
) as v(code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
join public.subjects s on s.slug = 'drawing-techniques'
on conflict (code) do nothing;

insert into public.entries (subject_id, code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
select s.id, v.*
from (values
    (
    '004-01',
    'pixels-vectors-and-grids',
    'Pixels, Vectors, and Grids',
    '2026-09-02'::date,
    'Digital images are built from systems.',
    'Raster images store colored samples, vectors store mathematical relationships, and grids organize how elements share a space — each system leaves its fingerprints on the result.',
    $j$["Resolution affects raster detail and scale.","Vectors preserve relationships across sizes.","A grid makes alignment and rhythm inspectable."]$j$::jsonb,
    $j$["Zoom in to see how a system changes at a different scale.","Treat alignment as a decision, not a default."]$j$::jsonb,
    'Make one small graphic in both raster and vector formats and note what each makes easier or harder.',
    'Understanding the representation explains the result.',
    1
  ),
    (
    '004-02',
    'color-as-data',
    'Color as Data',
    '2026-09-09'::date,
    'Color on screen is encoded, mixed, and read.',
    'Digital color models are ways of describing light and relationships; a palette is both a technical setting and a communication system at the same time.',
    $j$["Contrast supports legibility and hierarchy.","Color relationships can be complementary, analogous, or intentionally dissonant.","Screens and contexts alter perception."]$j$::jsonb,
    $j$["Test color on the actual background where it will appear.","Use one accent to signal action or importance."]$j$::jsonb,
    'Build a five-color palette with one action color and write the role of each.',
    'A palette is a system of signals, not a decoration.',
    2
  ),
    (
    '004-03',
    'layers-and-compositing',
    'Layers and Compositing',
    '2026-09-16'::date,
    'Building images non-destructively.',
    'Layers separate decisions so they can be tested and revised — opacity, masks, and blend modes define how those decisions interact in one frame.',
    $j$["Order changes what is visible.","Masks reveal selectively without destroying source material.","Compositing balances clarity with depth."]$j$::jsonb,
    $j$["Name layers by role and keep the hierarchy legible.","Toggle layers to find which decision is carrying the composition."]$j$::jsonb,
    'Rebuild a simple composition with at least four labeled layers and document the order.',
    'Layers make complexity manageable and mistakes reversible.',
    3
  ),
    (
    '004-04',
    'type-and-screen-space',
    'Type and Screen Space',
    '2026-09-23'::date,
    'Typography as a graphic object with behavior.',
    'On screen, text has to stay readable across devices and distances; hierarchy comes from size, spacing, contrast, and grouping.',
    $j$["Line length affects reading pace.","Weight and contrast establish hierarchy.","Responsive type must adapt without losing relationships."]$j$::jsonb,
    $j$["Inspect the design at small and large sizes.","Use whitespace to separate clusters of content."]$j$::jsonb,
    'Design one information panel — heading, body, metadata — and test it at two widths.',
    'Screen typography is spatial design: it routes how information is found.',
    4
  ),
    (
    '004-05',
    'motion-and-feedback',
    'Motion and Feedback',
    '2026-09-30'::date,
    'Interaction gives a static graphic a timeline.',
    'Motion can signal cause and effect, reveal hierarchy, or acknowledge an action — but it needs a clear purpose and a safe speed.',
    $j$["Transitions should preserve spatial continuity.","Feedback should be immediate and legible.","Reduced motion is a valid user preference."]$j$::jsonb,
    $j$["Describe the state change before choosing an animation.","Keep looping movement rare and quiet."]$j$::jsonb,
    'Storyboard a three-step interaction and label the feedback the user receives at each step.',
    'Motion shows a system responding — it is not decoration added afterward.',
    5
  ),
    (
    '004-06',
    'rendering-and-delivery',
    'Rendering and Delivery',
    '2026-10-07'::date,
    'The image has to survive the trip to the viewer’s device.',
    'Export settings, file formats, compression, and responsive behavior all shape the graphic that actually arrives — sometimes more than the edit itself.',
    $j$["Choose formats according to content and use.","Compression trades file weight against fidelity.","Testing the delivered artifact catches issues the source hides."]$j$::jsonb,
    $j$["Check sharpness, loading, and contrast on a real viewport.","Keep the source version separate from delivery versions."]$j$::jsonb,
    'Export one graphic for web delivery and write down the format, dimensions, and tradeoffs.',
    'Delivery is part of the assignment: performance and fidelity both count.',
    6
  )
) as v(code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
join public.subjects s on s.slug = 'computer-graphics'
on conflict (code) do nothing;

insert into public.entries (subject_id, code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
select s.id, v.*
from (values
    (
    '005-01',
    'signs-and-symbols',
    'Signs and Symbols',
    '2026-09-04'::date,
    'How a mark becomes meaningful.',
    'A sign points, resembles, or becomes associated with something else — and context and culture decide how an audience actually reads it.',
    $j$["Symbols depend on conventions and experience.","Icons use resemblance while indexes use connection.","Meaning shifts across contexts."]$j$::jsonb,
    $j$["Ask what the audience must already know.","Separate what a symbol depicts from what it does."]$j$::jsonb,
    'Collect three signs from daily life and classify how each one creates meaning.',
    'Shared symbols make invisible ideas available to an audience.',
    1
  ),
    (
    '005-02',
    'hierarchy-and-attention',
    'Hierarchy and Attention',
    '2026-09-11'::date,
    'Which element speaks first, second, and third.',
    'Hierarchy is shaped by scale, contrast, placement, density, and repetition — it is how an artifact helps its audience decide what matters.',
    $j$["Visual weight is relational, not absolute.","Grouping tells the viewer which items belong together.","An intentional sequence reduces search effort."]$j$::jsonb,
    $j$["Squint or blur the composition to see the hierarchy.","Name the first action you want the viewer to take."]$j$::jsonb,
    'Reorder the elements in a simple poster so the intended message lands within three steps.',
    'Hierarchy is choreography for attention.',
    2
  ),
    (
    '005-03',
    'typography-as-voice',
    'Typography as Voice',
    '2026-09-18'::date,
    'Letters carry tone before they are read word by word.',
    'Typeface, weight, spacing, and case change how a message feels and how quickly it can be read — type speaks before its words do.',
    $j$["Typography has both a semantic and an expressive role.","Consistency builds trust; contrast builds distinction.","Legibility is an ethical part of communication."]$j$::jsonb,
    $j$["Compare the same words in three typographic voices.","Check body copy at the size people will actually read it."]$j$::jsonb,
    'Set one short message in three typographic treatments and annotate the voice of each.',
    'Type makes language visible, audible in the mind, and emotionally situated.',
    3
  ),
    (
    '005-04',
    'color-and-context',
    'Color and Context',
    '2026-09-25'::date,
    'A color’s meaning depends on what surrounds it.',
    'A color’s function changes with its neighbors, its material, the culture, and the purpose — and accessible contrast keeps the signal available to everyone.',
    $j$["Color can encode categories and states.","Contrast is a relationship between foreground and background.","Meaning should never rely on color alone."]$j$::jsonb,
    $j$["Pair color with text, shape, or position.","Test the design under different light and display conditions."]$j$::jsonb,
    'Design three status indicators that stay understandable in grayscale.',
    'Color works best when it supports a larger system of meaning.',
    4
  ),
    (
    '005-05',
    'image-and-sequence',
    'Image and Sequence',
    '2026-10-02'::date,
    'Selection and order change the story.',
    'Cropping, juxtaposition, repetition, and pacing all steer interpretation — a sequence can create comparison, tension, or cause and effect.',
    $j$["Context changes an image’s meaning.","A crop is an argument about what matters.","Sequence can create rhythm, tension, or resolution."]$j$::jsonb,
    $j$["Describe the transition between two images.","Notice what the sequence asks the viewer to remember."]$j$::jsonb,
    'Arrange four images into two different sequences and write the story each one suggests.',
    'Even still images are temporal — order is part of the message.',
    5
  ),
    (
    '005-06',
    'communicating-with-clarity',
    'Communicating with Clarity',
    '2026-10-09'::date,
    'A message is a promise: the audience should find the meaning you intended.',
    'Clarity is not blandness — it is a balance of invitation, context, and just enough structure for an audience to act.',
    $j$["Clarity depends on audience, situation, and purpose.","Consistency lowers cognitive load.","Testing with another person exposes hidden assumptions."]$j$::jsonb,
    $j$["Let someone explain the message before you explain it.","Keep one primary action visible."]$j$::jsonb,
    'Test a small visual message with one person: record the first thing they noticed and the first thing they missed.',
    'Clear beats clever — and with care it can be both.',
    6
  )
) as v(code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)
join public.subjects s on s.slug = 'visual-communication'
on conflict (code) do nothing;

-- ============================================================
-- JOURNAL — "life updates" seed posts
-- ============================================================
insert into public.journal_posts (legacy_id, entry_date, title, body) values
  ('j-01', '2026-09-30'::date, 'Folder #001 is halfway done', 'Five entries in and the English folder finally feels like a real file. Next up: rhetoric and audience, then the writing note.'),
  ('j-02', '2026-09-18'::date, 'New desk setup', 'Moved the lamp closer and pinned the progress board above the desk. Suddenly documenting assignments doesn’t feel like a chore.'),
  ('j-03', '2026-09-05'::date, 'Started the case file', 'Built this little site to keep every assignment in one place — five folders, thirty entries, and pictures for all of them. Let’s see how far it goes.')
on conflict (legacy_id) do nothing;

-- ============================================================
-- PROFILE — the single profile row
-- ============================================================
insert into public.profile (id, name, case_number, "sign", dob, citizen, motto, extra, note_title, note_text, fandoms) values
  (1, 'Fiona Audrey Cuang', '26002600', 'Leo', 'August 2nd, 2008', 'Indonesia', 'Jealousy is the biggest form of motivation.', 'always overthinking', 'NOTE!!', 'this is where I keep every assignment — in one folder.', $j$["murder drones","the amazing digital circus","magical girl anime","many more"]$j$::jsonb)
on conflict (id) do nothing;
