// Regenerates supabase/seed.sql from the current src/data files so the
// database always starts with the same content the site ships with.
//
//   node scripts/gen-seed.mjs
//
// The data files are TypeScript, so they are transpiled to a temp folder
// with the project's own TypeScript compiler first, then imported here.

import { execFileSync } from 'node:child_process';
import { mkdirSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const temp = join(root, '.tmp-seed');
const require = createRequire(import.meta.url);

// --- transpile src/data/*.ts to plain ESM ------------------------------------
const sources = ['cases.ts', 'extras.ts', 'profile.ts'].map((f) => join(root, 'src/data', f));
for (const file of sources) {
  if (!existsSync(file)) throw new Error(`missing ${file}`);
}
rmSync(temp, { recursive: true, force: true });
mkdirSync(temp, { recursive: true });
const tsc = join(dirname(require.resolve('typescript/package.json')), 'bin', 'tsc');
execFileSync(process.execPath, [tsc, ...sources, '--ignoreConfig', '--outDir', temp, '--module', 'es2020', '--target', 'es2020'], { stdio: 'inherit' });

const { courses } = await import(pathToFileURL(join(temp, 'cases.js')).href);
const { journalSeed } = await import(pathToFileURL(join(temp, 'extras.js')).href);
const { profile } = await import(pathToFileURL(join(temp, 'profile.js')).href);

// --- SQL helpers --------------------------------------------------------------
const q = (text) => String(text).replace(/'/g, "''");
const json = (value) => `$j$${JSON.stringify(value)}$j$::jsonb`;

// --- subjects + entries -------------------------------------------------------
const subjectRows = [];
const entryBlocks = [];

courses.forEach((course, courseIndex) => {
  subjectRows.push(
    `  ('${q(course.slug)}', '${q(course.caseNumber)}', '${q(course.title)}', '${q(course.shortTitle)}', '${q(course.description)}', '${q(course.folderNote)}', '${q(course.icon)}', ${courseIndex + 1})`,
  );
  const rows = course.entries.map((entry, entryIndex) => {
    const values = [
      `'${q(entry.id)}'`,
      `'${q(entry.slug)}'`,
      `'${q(entry.title)}'`,
      `'${entry.date}'::date`,
      `'${q(entry.about)}'`,
      `'${q(entry.description)}'`,
      json(entry.keyPoints),
      json(entry.notes),
      `'${q(entry.task)}'`,
      `'${q(entry.wrapUp)}'`,
      String(entryIndex + 1),
    ].join(',\n    ');
    return `    (\n    ${values}\n  )`;
  });
  entryBlocks.push(
    `insert into public.entries (subject_id, code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)\n` +
    `select s.id, v.*\n` +
    `from (values\n${rows.join(',\n')}\n) as v(code, slug, title, entry_date, about, description, key_points, notes, task, wrap_up, sort_order)\n` +
    `join public.subjects s on s.slug = '${course.slug}'\n` +
    `on conflict (code) do nothing;`,
  );
});

// --- journal + profile --------------------------------------------------------
const journalRows = journalSeed
  .map((post) => `  ('${q(post.id)}', '${post.date}'::date, '${q(post.title)}', '${q(post.body)}')`)
  .join(',\n');

const profileRow = [
  '1',
  `'${q(profile.name)}'`,
  `'${q(profile.caseNumber)}'`,
  `'${q(profile.sign)}'`,
  `'${q(profile.dob)}'`,
  `'${q(profile.citizen)}'`,
  `'${q(profile.motto)}'`,
  `'${q(profile.extra)}'`,
  `'${q(profile.noteTitle)}'`,
  `'${q(profile.noteText)}'`,
  json(profile.fandoms),
].join(', ');

// --- assemble -----------------------------------------------------------------
const header = `-- CASE FILE — assignment vlog · seed data
-- GENERATED by scripts/gen-seed.mjs from src/data/cases.ts, extras.ts, profile.ts.
-- Regenerate with:  node scripts/gen-seed.mjs
-- Safe to run more than once (every statement is "on conflict do nothing").
-- Run AFTER supabase/schema.sql.`;

const sql = `${header}

-- ============================================================
-- SUBJECTS — the five course folders
-- ============================================================
insert into public.subjects (slug, case_number, title, short_title, description, folder_note, icon, sort_order) values
${subjectRows.join(',\n')}
on conflict (slug) do nothing;

-- ============================================================
-- ENTRIES — every assignment (subject link resolved by slug)
-- ============================================================
${entryBlocks.join('\n\n')}

-- ============================================================
-- JOURNAL — "life updates" seed posts
-- ============================================================
insert into public.journal_posts (legacy_id, entry_date, title, body) values
${journalRows}
on conflict (legacy_id) do nothing;

-- ============================================================
-- PROFILE — the single profile row
-- ============================================================
insert into public.profile (id, name, case_number, "sign", dob, citizen, motto, extra, note_title, note_text, fandoms) values
  (${profileRow})
on conflict (id) do nothing;
`;

writeFileSync(join(root, 'supabase', 'seed.sql'), sql.replace(/\r\n/g, '\n'), 'utf8');
rmSync(temp, { recursive: true, force: true });
console.log(`wrote supabase/seed.sql (${courses.length} subjects, ${courses.reduce((n, c) => n + c.entries.length, 0)} entries, ${journalSeed.length} journal posts, 1 profile)`);
